import styles from '../styles/styles.module.css';
import Head from 'next/head';
import Link from 'next/link';

export default function about() {
  return (
    <>
      <Head>
        <title>Brennan's Portfolio | About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <nav className={styles.navContainer}>
            <div className={styles.logo}>BH</div>
          <ul className={styles.navList}>
            <Link href="/" className={styles.navItem}>
              Home
            </Link>
            <Link href="/about" className={styles.navItem}>
              About Me
            </Link>
            <Link href="/projects" className={styles.navItem}>
              Projects
            </Link>
            <Link href="/resume" className={styles.navItem}>
              Resume
            </Link>
            <Link href="/contact" className={styles.navItem}>
              Contact
            </Link>
          </ul>
        </nav>
      <div className={styles.containerAbout1}>
        <div className={styles.about_parent}>
          <div className={styles.aboutMe1}  >About Me</div>
          <div className={styles.containerP1}  >
            Hi, my name is Brennan Holmes, I am currently taking a diploma in{' '}
            <br />
            Web Development at NSCC. Upon graduation in June 2023 I would like
            <br />
            to secure a position as a Junior Programer to gain experience and{' '}
            <br />
            grow within a company.
          </div>
          <div>
            <h3 className={styles.techSkills1} >Technology's that I've learned.</h3>
            <ul className={styles.skills1}>
              <li>JavaScript</li>
              <li>HTML / CSS</li>
              <li>React</li>
              <li>Laravel</li>
              <li>MySQL</li>
              <li>MongoDB</li>
            </ul>
          </div>
        </div>
      </div>
      </div>
      <footer className={styles.footer}><div>Made with ❤️ by Brennan Holmes</div></footer>
    </>
  );
}
