import Head from 'next/head';
import styles from '../styles/styles.module.css';
import Link from 'next/link';

export default function contact() {
  return (
    <>
      <Head>
        <title>Brennan's Portfolio | Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <nav className={styles.navContainer}>
            <div className={styles.logo}>BH</div>
          <ul className={styles.navList}>
            <Link href="/" className={styles.navItem}>
              Home
            </Link>
            <Link href="/about" className={styles.navItem}>
              About Me
            </Link>
            <Link href="/projects" className={styles.navItem}>
              Projects
            </Link>
            <Link href="/resume" className={styles.navItem}>
              Resume
            </Link>
            <Link href="/contact" className={styles.navItem}>
              Contact
            </Link>
          </ul>
        </nav>
      </div>
      <form
        // action="https://formbold.com/s/FORM_ID"
        method="POST"
        className={styles.form}
      >
        <div className="formbold-mb-5">
          <input
            type="text"
            name="name"
            id="name"
            placeholder="Full Name"
            className={styles.formboldFormInput}
          />
        </div>
        <div className="formbold-mb-5">
          <input
            type="email"
            name="email"
            id="email"
            placeholder="Enter your email"
            className={styles.formboldFormInput}
          />
        </div>
        <div className="formbold-mb-5">
          <input
            type="text"
            name="subject"
            id="subject"
            placeholder="Enter your subject"
            className={styles.formboldFormInput}
          />
        </div>
        <div className="formbold-mb-5">
          <textarea
            rows="6"
            name="message"
            id="message"
            placeholder="Enter your message"
            className={styles.formboldFormInput}
          ></textarea>
        </div>
        <div>
          <button className={styles.formboldBtn}>Submit</button>
        </div>
      </form>
      <footer className={styles.footer}>Made with ❤️ by Brennan Holmes</footer>
    </>
  );
}
