import styles from '../styles/styles.module.css';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

export default function projects() {
  return (
    <>
      <Head>
        <title>Brennan's Portfolio | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <nav className={styles.navContainer}>
          <div className={styles.logo}>BH</div>
          <ul className={styles.navList}>
            <Link href="/" className={styles.navItem}>
              Home
            </Link>
            <Link href="/about" className={styles.navItem}>
              About Me
            </Link>
            <Link href="/projects" className={styles.navItem}>
              Projects
            </Link>
            <Link href="/resume" className={styles.navItem}>
              Resume
            </Link>
            <Link href="/contact" className={styles.navItem}>
              Contact
            </Link>
          </ul>
        </nav>
        <div>
          <h3 className={styles.viewProjects}>View My Projects</h3>
        </div>
        <div className={styles.containerImgs}>
          <div className={styles.item_div}>
            <Link href="https://github.com/Brennan-Holmes">
              <p className={styles.pHome}>
                In my co-op that I did I made a ticketing system, which was CRUD
                based
                <br />
                and used a PostgreSQL database. I also used ReactJS to create
                the front end. <br />I used JavaScript to create the backend.
              </p>
              <Image
                src="/ilya-pavlov-OqtafYT5kTw-unsplash.jpg"
                width={300}
                height={300}
                quality={80}
                alt="Image not working"
                className={styles.img}
              />
            </Link>
          </div>
          <div className={styles.item_div}>
            <Link href="https://github.com/Brennan-Holmes">
              <p className={styles.pHome}>
                In my Full Stack course we did a final assignment where we had
                to create a form for sign up and sign in.
                <br />
                We also had to create a CRUD based application that used a
                MongoDB database. <br />I used ReactJS to create the front end
                and used JavaScript to create the backend which then connected
                to an API.
              </p>
              <Image
                src="/tianyi-ma-WiONHd_zYI4-unsplash.jpg"
                width={300}
                height={300}
                quality={80}
                alt="Image not working"
                className={styles.img}
              />
            </Link>
          </div>
          <div className={styles.item_div}>
            <Link href="https://github.com/Brennan-Holmes">
              <p className={styles.pHome}>
                In my Special Topics course we learned how Electron works, and
                how to create a desktop application.
                <br />
                We also learned how IPCMain to render works and how to use it to
                render to the frontend.
              </p>
              <Image
                src="/onur-binay-_yC2htzMYnI-unsplash.jpg"
                width={300}
                height={300}
                quality={80}
                alt="Image not working"
                className={styles.img}
              />
            </Link>
          </div>
          <div className={styles.item_div}>
            <Link href="https://github.com/Brennan-Holmes">
              <p className={styles.pHome}>
                In my Special Topics course we learned how Electron works, and
                how to create a desktop application.
                <br />
                We also learned how IPCMain to render works and how to use it to
                render to the frontend.
              </p>
              <Image
                src="/onur-binay-_yC2htzMYnI-unsplash.jpg"
                width={300}
                height={300}
                quality={80}
                alt="Image not working"
                className={styles.img}
              />
            </Link>
          </div>
          <div className={styles.item_div}>
            <Link href="https://github.com/Brennan-Holmes">
              <p className={styles.pHome}>
                In my Special Topics course we learned how Electron works, and
                how to create a desktop application.
                <br />
                We also learned how IPCMain to render works and how to use it to
                render to the frontend.
              </p>
              <Image
                src="/onur-binay-_yC2htzMYnI-unsplash.jpg"
                width={300}
                height={300}
                quality={80}
                alt="Image not working"
                className={styles.img}
              />
            </Link>
          </div>
          <div className={styles.item_div}>
            <Link href="https://github.com/Brennan-Holmes">
              <p className={styles.pHome}>
                In my Special Topics course we learned how Electron works, and
                how to create a desktop application.
                <br />
                We also learned how IPCMain to render works and how to use it to
                render to the frontend.
              </p>
              <Image
                src="/onur-binay-_yC2htzMYnI-unsplash.jpg"
                width={300}
                height={300}
                quality={80}
                alt="Image not working"
                className={styles.img}
              />
            </Link>
          </div>
          <div className={styles.item_div}>
            <Link href="https://github.com/Brennan-Holmes">
              <p className={styles.pHome}>
                In my Special Topics course we learned how Electron works, and
                how to create a desktop application.
                <br />
                We also learned how IPCMain to render works and how to use it to
                render to the frontend.
              </p>
              <Image
                src="/onur-binay-_yC2htzMYnI-unsplash.jpg"
                width={300}
                height={300}
                quality={80}
                alt="Image not working"
                className={styles.img}
              />
            </Link>
          </div>
          <div className={styles.item_div}>
            <Link href="https://github.com/Brennan-Holmes">
              <p className={styles.pHome}>
                In my Special Topics course we learned how Electron works, and
                how to create a desktop application.
                <br />
                We also learned how IPCMain to render works and how to use it to
                render to the frontend.
              </p>
              <Image
                src="/onur-binay-_yC2htzMYnI-unsplash.jpg"
                width={300}
                height={300}
                quality={80}
                alt="Image not working"
                className={styles.img}
              />
            </Link>
          </div>
        </div>
      </div>
      <footer className={styles.footer}>
        <div>Made with ❤️ by Brennan Holmes</div>
      </footer>
    </>
  );
}
